Update clap to 4.2.7
Previous version would not compile on stable toolchain
because of rustix dependency:
```
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /home/mdank/.cargo/registry/src/github.com-1ecc6299db9ec823/rustix-0.36.6/src/lib.rs:99:26
   |
99 | #![cfg_attr(rustc_attrs, feature(rustc_attrs))]
   |
```
```
$ cargo tree -i rustix
rustix v0.36.6
└── is-terminal v0.4.2
    └── clap v4.0.32
        └── prop-builder v0.1.0 (/home/mdank/repos/datarevenue/DEFI/prop-builder)
```

After upgrading clap, rustix also got updated and no longer
causes an error:
```
$ cargo tree -i rustix
rustix v0.37.19
└── is-terminal v0.4.7
    └── anstream v0.3.2
        └── clap_builder v4.2.7
            └── clap v4.2.7
                └── prop-builder v0.1.0 (/home/mdank/repos/datarevenue/DEFI/prop-builder)
```